/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as TreasureChestRouteImport } from './routes/treasure-chest'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as KeepsakesRouteImport } from './routes/keepsakes'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorySlugRouteImport } from './routes/story.$slug'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasureChestRoute = TreasureChestRouteImport.update({
  id: '/treasure-chest',
  path: '/treasure-chest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepsakesRoute = KeepsakesRouteImport.update({
  id: '/keepsakes',
  path: '/keepsakes',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorySlugRoute = StorySlugRouteImport.update({
  id: '/story/$slug',
  path: '/story/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/inspiration': typeof InspirationRoute
  '/keepsakes': typeof KeepsakesRoute
  '/profile': typeof ProfileRoute
  '/treasure-chest': typeof TreasureChestRoute
  '/world': typeof WorldRoute
  '/story/$slug': typeof StorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/inspiration': typeof InspirationRoute
  '/keepsakes': typeof KeepsakesRoute
  '/profile': typeof ProfileRoute
  '/treasure-chest': typeof TreasureChestRoute
  '/world': typeof WorldRoute
  '/story/$slug': typeof StorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/inspiration': typeof InspirationRoute
  '/keepsakes': typeof KeepsakesRoute
  '/profile': typeof ProfileRoute
  '/treasure-chest': typeof TreasureChestRoute
  '/world': typeof WorldRoute
  '/story/$slug': typeof StorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adventure'
    | '/inspiration'
    | '/keepsakes'
    | '/profile'
    | '/treasure-chest'
    | '/world'
    | '/story/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adventure'
    | '/inspiration'
    | '/keepsakes'
    | '/profile'
    | '/treasure-chest'
    | '/world'
    | '/story/$slug'
  id:
    | '__root__'
    | '/'
    | '/adventure'
    | '/inspiration'
    | '/keepsakes'
    | '/profile'
    | '/treasure-chest'
    | '/world'
    | '/story/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventureRoute: typeof AdventureRoute
  InspirationRoute: typeof InspirationRoute
  KeepsakesRoute: typeof KeepsakesRoute
  ProfileRoute: typeof ProfileRoute
  TreasureChestRoute: typeof TreasureChestRoute
  WorldRoute: typeof WorldRoute
  StorySlugRoute: typeof StorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasure-chest': {
      id: '/treasure-chest'
      path: '/treasure-chest'
      fullPath: '/treasure-chest'
      preLoaderRoute: typeof TreasureChestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keepsakes': {
      id: '/keepsakes'
      path: '/keepsakes'
      fullPath: '/keepsakes'
      preLoaderRoute: typeof KeepsakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$slug': {
      id: '/story/$slug'
      path: '/story/$slug'
      fullPath: '/story/$slug'
      preLoaderRoute: typeof StorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventureRoute: AdventureRoute,
  InspirationRoute: InspirationRoute,
  KeepsakesRoute: KeepsakesRoute,
  ProfileRoute: ProfileRoute,
  TreasureChestRoute: TreasureChestRoute,
  WorldRoute: WorldRoute,
  StorySlugRoute: StorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
